version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    # https://github.com/docker/compose/issues/1393#issuecomment-99988242
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    depends_on:
     - db
