---
resources:
  - name: git-repository
    type: git
    source:
      uri: "https://github.com/abisz/snipper.git"
      branch: master
  - name: dockerfile
    type: git
    source:
      uri: "https://github.com/abisz/snipper.git"
      branch: master
      paths: [Dockerfile]
  - name: docker-image
    type: docker-image
    source:
      repository: abisz/snipper
      email: {{docker_email}}
      username: {{docker_username}}
      password: {{docker_password}}


jobs:
- name: build-stage
  plan:
  - get: dockerfile
    trigger: true
  - put: docker-image
    params: {build: dockerfile}

- name: commit-stage
  plan:
  - get: git-repository
    trigger: true
  - task: run-tests
    config:
      platform: linux

      inputs:
      - name: git-repository

      image_resource:
        type: docker-image
        source:
          repository: abisz/snipper

      params:
        RAILS_ENV: test

      run:
        path: sh
        dir: git-repository
        args:
          - -exc
          - |
            bundle install
            rails db:setup
            rails test

- name: acceptance-stage
  serial: true
  plan:
  - get: git-repository
    trigger: true
    passed: [commit-stage]
  - task: run-acceptance-tests
    config:
      platform: linux

      inputs:
      - name: git-repository

      image_resource:
        type: docker-image
        source:
          repository: abisz/snipper

      params:
        RAILS_ENV: test

      run:
        path: sh
        dir: git-repository
        args:
          - -exc
          - |
            bundle install
            rails db:setup
            rails test

- name: deploy-stage
  serial: true
  plan:
  - get: git-repository
    trigger: true
    passed: [acceptance-stage]
  - task: deploy-heroku
    params:
      HEROKU_EMAIL: {{heroku_email}}
      HEROKU_TOKEN: {{heroku_token}}
    config:
      platform: linux

      image_resource:
        type: docker-image
        source: { repository: concourse/bosh-cli }

      inputs:
        - name: git-repository

      run:
        path: sh
        dir: git-repository
        args:
          - -exc
          - |
            cat > /root/.netrc <<EOF
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_TOKEN
            EOF
            git push https://git.heroku.com/mighty-wildwood-45498.git master:refs/heads/master
