default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development: &default
  adapter: postgresql
  encoding: unicode
  database: snipper_development
  pool: 5
  username: postgres
  password:
  host: db

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: snipper_production
  username: snipper
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>
